version: '3.7'
services:

    app:
        build:
            context: .
            dockerfile: ./docker/Dockerfile
        restart: unless-stopped
        tty: true
        working_dir: /var/www
        depends_on:
            - database
            - webserver
        volumes:
            - ./:/var/www
        networks:
            - arent

    webserver:
        image: nginx:alpine
        restart: unless-stopped
        tty: true
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./:/var/www
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - arent

    database:
        image: mysql:5.7.38
        command: --default-authentication-plugin=mysql_native_password --innodb-use-native-aio=0
        restart: unless-stopped
        tty: true
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: 'arent'
        volumes:
            - db:/var/lib/mysql
        networks:
            - arent
networks:
    arent:

volumes:
    db:
